// js/data_pois.js
const POI_SYMBOLS = { TOWN: 'T', CAVE: 'C', FOREST: 'F', RUINS: 'R', SHRINE: 'S', LATRINE: 'L', SHOP: '$' };

const poiDataDefinitions = {
    [POI_SYMBOLS.TOWN]: { name: "a Quaint Village", description: "You see a small, bustling village. Smoke rises from chimneys, and you hear the distant sound of a blacksmith's hammer.", actions: [ { text: "Talk to Villagers", handler: "talkToVillagers" }, { text: "Visit General Store", handler: "visitShop", shopType: "general" }, { text: "Use Outhouse", handler: "useOuthouse" }, { text: "Leave Village", handler: "leavePOI" } ], encounterChance: 0.05, enemies: ["Grumpy Farmer (Annoyed)", "Street Urchin (Pickpocket attempt)"] },
    [POI_SYMBOLS.SHOP]: { name: "a Bustling Marketplace Stall", description: "Various goods are on display. The merchant eyes you expectantly.", actions: [ { text: "Browse Wares", handler: "visitShop", shopType: "general" }, { text: "Leave Stall", handler: "leavePOI" }], encounterChance: 0, enemies: [] },
    [POI_SYMBOLS.LATRINE]: { name: "a Crude Latrine", description: "A roughly dug pit with a wooden seat. It's not pleasant, but it's functional.", actions: [ { text: "Use Latrine", handler: "useOuthouse"}, {text: "Leave", handler: "leavePOI"}], encounterChance: 0, enemies: [] },
    [POI_SYMBOLS.CAVE]: { name: "a Dark Cave Entrance", description: "A chill emanates from the dark maw of this cave. Strange echoes can be heard from within.", actions: [ { text: "Explore Deeper", handler: "exploreCave", rewards: [{ itemName: "Glowing Mushroom", quantity: 1, type: "misc", chance: 0.3, value: 1, price: 3 }], triggersCombat: true, combatEncounterChance: 0.5, combatEnemies: ["Goblin Scout", "Giant Spider"] }, { text: "Search Entrance", handler: "searchCaveEntrance", rewards: [{ itemName: "Old Coin", quantity: () => getRandomInt(1,3), type: "currency", chance: 0.6, value: 1, price: 1 }, { itemName: "Rusty Dagger", quantity: 1, type: "weapon", slot:"hands", strength_bonus: 1, chance: 0.2, value: 5, price: 15, equippable: true }], triggersCombat: true, combatEncounterChance: 0.2, combatEnemies: ["Cave Bat Swarm"] }, { text: "Leave Cave", handler: "leavePOI" } ], encounterChance: 0.1, enemies: ["Cave Bat Swarm"] },
    [POI_SYMBOLS.FOREST]: { name: "a Dense Forest", description: "The trees stand tall and close together, sunlight dappling the forest floor. The air is thick with the scent of pine and damp earth.", actions: [ { text: "Follow Animal Tracks", handler: "followTracks", triggersCombat: true, combatEncounterChance: 0.4, combatEnemies: ["Wolf"] }, { text: "Forage for Herbs", handler: "forageHerbs", rewards: [{ itemName: "Healing Herb", quantity: () => getRandomInt(1,2), type: "consumable", chance: 0.7, value: 3, price: 10 }, {itemName: "Common Berries", quantity: () => getRandomInt(2,5), type: "food", chance: 0.5, value: 0, price: 1}] }, { text: "Leave Forest", handler: "leavePOI" } ], encounterChance: 0.2, enemies: ["Bandit Ambusher"] },
    [POI_SYMBOLS.RUINS]: { name: "Crumbling Ancient Ruins", description: "Stone structures, weathered by time, jut out from the overgrown landscape. A sense of forgotten history hangs in the air.", actions: [ { text: "Investigate Structures", handler: "investigateRuins", rewards: [{itemName: "Ancient Tablet Fragment", quantity:1, type:"quest_item", chance: 0.25, value: 0, price: 0}], triggersCombat: true, combatEncounterChance: 0.3, combatEnemies: ["Restless Spirit"] },  { text: "Search for Artifacts", handler: "searchArtifacts", rewards: [{itemName: "Cracked Gemstone", quantity:1, type:"valuable", chance: 0.4, value: 20, price: 50}, {itemName: "Pottery Shard", quantity:() => getRandomInt(1,4), type:"misc", chance:0.6, value: 1, price: 2}] }, { text: "Leave Ruins", handler: "leavePOI" } ], encounterChance: 0.35, enemies: ["Restless Spirit", "Guardian Construct (Damaged)", "Treasure Hunter (Rival)"] },
    [POI_SYMBOLS.SHRINE]: { name: "a Serene Shrine", description: "A small, peaceful shrine stands here, dedicated to an unknown deity. Offerings of flowers and incense lie at its base.", actions: [ { text: "Offer a Prayer", handler: "offerPrayer", rewards: [{itemName: "Feeling of Peace", quantity:1, type:"buff_placeholder", chance:0.8, value: 0, price: 0}] }, { text: "Meditate Briefly", handler: "meditateShrine" }, { text: "Leave Shrine", handler: "leavePOI" } ], encounterChance: 0.0, enemies: [] }
};